### ISSUE TITLE
Support cargo's library name property

### ISSUE THREAD

**Issue by evant** [rust-windowing/android-ndk-rs#136]
If you have a specific library name specified in your Cargo.toml, it will change the name of the so file. ex:

```toml
[pacakge]
name = "foo"

[lib]
name = "bar"
```

```
cargo apk build
```

builds: `target/aarch64-linux-android/debug/bar.so`

and then errors with:
```
Error: Path "target/aarch64-linux-android/debug/foo.so" doesn't exist.
```
