### ISSUE TITLE
Conditionally generate manifest with cargo features

### ISSUE THREAD

**Issue by zarik5** [rust-windowing/android-ndk-rs#215]
cargo-apk should be able to use features (and maybe targets) to conditionally build the `AndroidManifest.xml`, in a similar way to gradle build flavors. My use-case is having different `runtime_libs` for different types of android devices.

Example: 

```toml
[package.metadata.android]
build_targets = ["aarch64-linux-android"]

[package.'cfg(feature = "oculus")'.metadata.android]
runtime_libs = "deps/openxr/oculus"

[package.'cfg(feature = "vive")'.metadata.android]
runtime_libs = "deps/openxr/vive"
```
