### ISSUE TITLE
Control over the AndroidManifest.xml package name

### ISSUE THREAD

**Issue by zjijz** [rust-windowing/android-ndk-rs#234]
Currently `cargo apk build` and `cargo apk run` will set the Android package name for you, to `"rust.<package name in Cargo.toml>"`.

Can we add a `Cargo.toml` property like `apk_name` that controls the APK package name in `AndroidManifest.xml`?

Something like:
```toml
[package.metadata.android]
apk_package = "com.blah.blahblah" # defaults to "rust.<package.name>"
# ...
```
that generates
```xml
<manifest package="com.blah.blahblah">...</manifest>
```
