### ISSUE TITLE
cargo-apk: Support `[env]` variables in `.cargo/config.toml`

### ISSUE THREAD

**Issue by ItsMeSKKYZ3R** [rust-windowing/android-ndk-rs#247]
Hello,

I'm trying to create an Android application with Rust and I use cargo-apk. But, when I set the `ANDROID_NDK_ROOT` env variable, cargo-apk shows me this error: `Error: Android NDK is not found. Please set the path to the Android NDK with $ANDROID_NDK_ROOT environment variable.`. I tried to set it with and without the dollar sign but nothing works.

Can you help me?

**Comment by ItsMeSKKYZ3R** [comment]
My config.toml file:

```toml
[env]
ANDROID_NDK_ROOT = { value = "C:\Users\nicol\AppData\Local\Android\Sdk\ndk\23.1.7779620", force = true }
ANDROID_SDK_ROOT = { value = "C:\Users\nicol\AppData\Local\Android\Sdk", force = true }
```
