### ISSUE TITLE
Signing release APKs on GitHub Actions?

### ISSUE THREAD

**Issue by torokati44** [rust-windowing/android-ndk-rs#326]
I have some difficulties signing my release builds on GitHub Actions due to https://github.com/rust-windowing/android-ndk-rs/pull/299.

A while ago, it was enough to have these secrets set up for GitHub Actions:

![Screenshot_20220814_224344](https://user-images.githubusercontent.com/288816/184554376-cd596c93-ad1a-45c6-a248-0a6f98e80519.png)

And then do this in the `.yml` config of the workflow:
```yaml
    - name: Decode keystore
      if: ${{ !github.event.pull_request.head.repo.fork }}
      env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
          echo $ENCODED_STRING | base64 -di > app/ruffle/androidkey.jks

    - name: Build release APK
      if: ${{ !github.event.pull_request.head.repo.fork }}
      run: |
        cd app
        ./gradlew assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

```

And have this in `build.gradle`:

```gradle
    signingConfigs {
        release {
            storeFile = file("androidkey.jks")
            storePassword System.getenv("SIGNING_STORE_PASSWORD")
            keyAlias System.getenv("SIGNING_KEY_ALIAS")
            keyPassword System.getenv("SIGNING_KEY_PASSWORD")
        }
    }
```
And I could build release `.apk`s on GitHub CI this way.

But now, I'm not sure how I could get these secrets into `Cargo.toml`, or how I could avoid having to do so.
Now I get this: `Error: Configure a release keystore via '[package.metadata.android.signing.release]'`
See: https://github.com/torokati44/ruffle-android/runs/7828734259?check_suite_focus=true
